// Code generated by aocgen; DO NOT EDIT.
package year2022

type Day01 struct{}

func (p Day01) PartA(lines []string) any {
	return "implement_me"
}

func (p Day01) PartB(lines []string) any {
	return "implement_me"
}
